gitops section 5

diff --git a/roles/setup_gitea/templates/rhde_gitops/production-kickstart.ks.j2 b/roles/setup_gitea/templates/rhde_gitops/production-kickstart.ks.j2
--- a/roles/setup_gitea/templates/rhde_gitops/production-kickstart.ks.j2
+++ b/roles/setup_gitea/templates/rhde_gitops/production-kickstart.ks.j2
@@ -538,24 +538,24 @@ restorecon -vFr /var/home/ansible
 
 ## This script is deployed by AAP but I keep it here in the KS for future reference
 
-#sudo cat << 'EOF' > /etc/greenboot/check/required.d/01-check-packages.sh
-##!/bin/bash
-#
-## List of required packages
-#required_packages=("python3-pip" "python3-inotify" "git")
-#
-## Check if each package is installed
-#for package in "\${required_packages[@]}"; do
-#    if ! rpm -q "\$package" &>/dev/null; then
-#        echo "Error: \$package is not installed."
-#        exit 1
-#    fi
-#done
-#
-#echo "All required packages are installed."
-#EOF
-#
-#chmod +x /etc/greenboot/check/required.d/01-check-packages.sh
+sudo cat << 'EOF' > /etc/greenboot/check/required.d/01-check-packages.sh
+#!/bin/bash
+
+# List of required packages
+required_packages=("python3-pip" "python3-inotify" "git")
+
+# Check if each package is installed
+for package in "\${required_packages[@]}"; do
+    if ! rpm -q "\$package" &>/dev/null; then
+        echo "Error: \$package is not installed."
+        exit 1
+    fi
+done
+
+echo "All required packages are installed."
+EOF
+
+chmod +x /etc/greenboot/check/required.d/01-check-packages.sh
 
 
 
